version: "3.8"
services:
  kitura:
    # image: "swift:bionic"
    build:
      context: docker
      dockerfile: kitura.dockerfile
    volumes: 
      - "./app:/app"
    working_dir: /app/stlib
    ports:
      - "8080:8080"